### ISSUE TITLE
DHT/Peer Exchange

### ISSUE THREAD

**Issue by iamadamreed** [cheatdeath/research-bittorrent#6]
Do you intend to continue your development of this to include DHT/Peer Exchange. The work you have done here has help me a lot in understanding BitTorrent in C#!

**Comment by iamadamreed** [comment]
I would recommend looking into https://github.com/bizzehdee/System.Net.Torrent

**Comment by iRajul** [comment]
@adamreed90  @cheatdeath  Can I replicate this project in C++ lanuage?

**Comment by seanoflynn** [comment]
@adamreed90 I don't plan on doing any more work on this for the foreseeable future. 

@iRajul Sure, if you want.

**Comment by iRajul** [comment]
@cheatdeath  I want to do this for learning purpose. Can you please brief me little bit about this project's make process. Is it GUI or commandline tool. after that I will continue on my own.

**Comment by seanoflynn** [comment]
If you download Xamarin Studio (https://www.xamarin.com/download) you should be able to open the project file (Research-BitTorrent.sln) in the IDE and then Build and Run. It's possible to build from the command line but more complicated – I've never used the command line tools.
