### ISSUE TITLE
Problem with link to tutorial

### ISSUE THREAD

**Issue by AlexO64** [cheatdeath/research-bittorrent#7]
Hello Sean,
I very like your bittorent project and was follow it about week or two, but suddenly the tutorial is offline( http://seanjoflynn.com/research/bittorrent ). I was using your research very hard so if you closed the page permanently could you be so kind to send me content of this page( http://seanjoflynn.com/research/bittorrent ) or what you still have. I was stupid to not back up your page at first place.
Thank you very much
Sincerely yours, Alex O

**Comment by seanoflynn** [comment]
Hey Alex,
Yeah my server is down. Sorry about that. I've attached the contents of that page.
Regards,
Sean
[bittorrent.zip](https://github.com/seanoflynn/research-bittorrent/files/1120321/bittorrent.zip)

**Comment by AlexO64** [comment]
Thank you very much, Sean!
You save my life. :-)
Alex
