### ISSUE TITLE
Writeup linked in readme is dead. 

### ISSUE THREAD

**Issue by Herbstein** [cheatdeath/research-bittorrent#8]
This project seems really interesting. I found a lot of praise for it on hackernews, and it's something I've been willing to learn for a long time. Any chance you've still got the text?

**Comment by seanoflynn** [comment]
My apologies. I'm trying to move my website over to aspnet core on Linux but it doesn't seem to be very stable. I've been too busy to fix it properly for the last few weeks. Here's a link to the content: https://github.com/seanoflynn/research-bittorrent/files/1120321/bittorrent.zip

**Comment by Herbstein** [comment]
No worries. Thanks for the link :)
